project_id = "rgehleqcubtmcwyipyvi"

[functions.beauty-assistant]
verify_jwt = false

[functions.bulk-product-upload]
verify_jwt = false

[functions.create-cod-order]
verify_jwt = false

[functions.get-order-status]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
